const QUEUE_TIMEOUT_MS = 90 * 1000;
const COUNTDOWN_SECONDS = 5;
const BATTLE_QUESTION_COUNT = 5;

const BATTLE_DURATION_SECONDS = {
  EASY: 120,
  MEDIUM: 180,
  HARD: 240,
  MIXED: 180,
};

const CODING_DURATION_SECONDS = {
  EASY: 600,
  MEDIUM: 900,
  HARD: 1200,
  MIXED: 900,
};

const PLAYERS_FOR_FORMAT = {
  ONE_V_ONE: 2,
  THREE_V_THREE: 6,
};

const BATTLE_XP = {
  WIN: 40,
  PARTICIPATION: 15,
  DRAW: 20,
};

module.exports = {
  QUEUE_TIMEOUT_MS,
  COUNTDOWN_SECONDS,
  BATTLE_QUESTION_COUNT,
  BATTLE_DURATION_SECONDS,
  CODING_DURATION_SECONDS,
  PLAYERS_FOR_FORMAT,
  BATTLE_XP,
};
