const USER_ROLES = ['STUDENT', 'MENTOR', 'ADMIN'];
const USER_STATUSES = ['ACTIVE', 'BLOCKED', 'DELETED'];
const CONTENT_STATUSES = ['DRAFT', 'PUBLISHED', 'ARCHIVED'];
const ACTIVE_STATUSES = ['ACTIVE', 'INACTIVE'];

const COURSE_LEVELS = ['BEGINNER', 'INTERMEDIATE', 'ADVANCED'];

const LESSON_TYPES = ['VIDEO', 'ARTICLE', 'QUIZ', 'CODING', 'LIVE_SESSION'];

const ENROLLMENT_STATUSES = ['ACTIVE', 'COMPLETED', 'PAUSED', 'DROPPED'];
const LESSON_PROGRESS_STATUSES = ['NOT_STARTED', 'IN_PROGRESS', 'COMPLETED'];

const ASSESSMENT_TYPES = [
  'LESSON_QUIZ',
  'COURSE_EXAM',
  'PRACTICE',
  'DAILY_CHALLENGE',
  'BATTLE',
];
const ASSESSMENT_MODES = ['QUIZ', 'CODING', 'MIXED'];
const DIFFICULTIES = ['EASY', 'MEDIUM', 'HARD', 'MIXED'];

const QUESTION_TYPES = [
  'SINGLE_CHOICE',
  'MULTIPLE_CHOICE',
  'TRUE_FALSE',
  'SHORT_TEXT',
  'CODING',
];

const ATTEMPT_CONTEXT_TYPES = [
  'LESSON',
  'COURSE',
  'PRACTICE',
  'DAILY_CHALLENGE',
  'BATTLE',
];
const ATTEMPT_STATUSES = [
  'IN_PROGRESS',
  'SUBMITTED',
  'EVALUATED',
  'EXPIRED',
  'CANCELLED',
];

const XP_TRANSACTION_TYPES = ['EARN', 'REVERSAL', 'ADMIN_ADJUSTMENT'];
const XP_SOURCE_TYPES = [
  'LESSON_COMPLETION',
  'COURSE_COMPLETION',
  'QUIZ',
  'PRACTICE',
  'DAILY_CHALLENGE',
  'BATTLE_WIN',
  'BATTLE_PARTICIPATION',
  'STREAK',
  'ACHIEVEMENT',
  'ADMIN',
];

const CHALLENGE_TYPES = [
  'ASSESSMENT',
  'COMPLETE_LESSONS',
  'ANSWER_QUESTIONS',
  'WIN_BATTLE',
  'EARN_XP',
];
const CHALLENGE_STATUSES = ['SCHEDULED', 'ACTIVE', 'COMPLETED', 'CANCELLED'];
const USER_CHALLENGE_STATUSES = [
  'NOT_STARTED',
  'IN_PROGRESS',
  'COMPLETED',
  'EXPIRED',
];

const BATTLE_FORMATS = ['ONE_V_ONE', 'THREE_V_THREE'];
const BATTLE_MODES = ['QUIZ', 'CODING', 'MIXED'];
const MATCH_TYPES = ['RANDOM', 'PRIVATE', 'INVITATION'];
const BATTLE_STATUSES = [
  'WAITING',
  'MATCHED',
  'STARTING',
  'IN_PROGRESS',
  'COMPLETED',
  'CANCELLED',
  'EXPIRED',
];
const PARTICIPANT_STATUSES = [
  'INVITED',
  'JOINED',
  'READY',
  'PLAYING',
  'COMPLETED',
  'LEFT',
];
const TEAMS = ['A', 'B'];
const WINNER_TYPES = ['USER', 'TEAM', 'DRAW'];

const MATCHMAKING_STATUSES = ['SEARCHING', 'MATCHED', 'CANCELLED', 'EXPIRED'];

const ACHIEVEMENT_CATEGORIES = [
  'LEARNING',
  'PRACTICE',
  'BATTLE',
  'STREAK',
  'XP',
  'COURSE',
];
const ACHIEVEMENT_METRICS = [
  'LESSONS_COMPLETED',
  'COURSES_COMPLETED',
  'BATTLES_WON',
  'QUESTIONS_CORRECT',
  'STREAK_DAYS',
  'TOTAL_XP',
];
const USER_ACHIEVEMENT_STATUSES = ['IN_PROGRESS', 'COMPLETED'];

const NOTIFICATION_TYPES = [
  'COURSE_UPDATE',
  'LESSON_REMINDER',
  'BATTLE_INVITATION',
  'BATTLE_MATCHED',
  'BATTLE_RESULT',
  'ACHIEVEMENT_UNLOCKED',
  'DAILY_CHALLENGE',
  'XP_REWARD',
  'SYSTEM',
];

const LEADERBOARD_PERIOD_TYPES = ['GLOBAL', 'WEEKLY', 'MONTHLY'];

const COMMUNITY_POST_TYPES = [
  'DISCUSSION',
  'QUESTION',
  'WIN',
  'REPLAY',
  'RESOURCE',
  'EVENT',
];
const COMMUNITY_CATEGORIES = [
  'GENERAL',
  'CODING',
  'DESIGN',
  'LANGUAGES',
  'MATH',
  'BATTLES',
  'CAREER',
];
const COMMUNITY_POST_STATUSES = ['ACTIVE', 'HIDDEN', 'DELETED'];
const COMMUNITY_ROOM_STATUSES = ['ACTIVE', 'ARCHIVED'];
const COMMUNITY_MEMBER_ROLES = ['OWNER', 'MEMBER'];

module.exports = {
  USER_ROLES,
  USER_STATUSES,
  CONTENT_STATUSES,
  ACTIVE_STATUSES,
  COURSE_LEVELS,
  LESSON_TYPES,
  ENROLLMENT_STATUSES,
  LESSON_PROGRESS_STATUSES,
  ASSESSMENT_TYPES,
  ASSESSMENT_MODES,
  DIFFICULTIES,
  QUESTION_TYPES,
  ATTEMPT_CONTEXT_TYPES,
  ATTEMPT_STATUSES,
  XP_TRANSACTION_TYPES,
  XP_SOURCE_TYPES,
  CHALLENGE_TYPES,
  CHALLENGE_STATUSES,
  USER_CHALLENGE_STATUSES,
  BATTLE_FORMATS,
  BATTLE_MODES,
  MATCH_TYPES,
  BATTLE_STATUSES,
  PARTICIPANT_STATUSES,
  TEAMS,
  WINNER_TYPES,
  MATCHMAKING_STATUSES,
  ACHIEVEMENT_CATEGORIES,
  ACHIEVEMENT_METRICS,
  USER_ACHIEVEMENT_STATUSES,
  NOTIFICATION_TYPES,
  LEADERBOARD_PERIOD_TYPES,
  COMMUNITY_POST_TYPES,
  COMMUNITY_CATEGORIES,
  COMMUNITY_POST_STATUSES,
  COMMUNITY_ROOM_STATUSES,
  COMMUNITY_MEMBER_ROLES,
};
