"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _learn_course_card from './learn-course-card.bones.json'
import _practice_card from './practice-card.bones.json'
import _community_message from './community-message.bones.json'

configureBoneyard({"color":"rgba(138, 122, 109, 0.14)","darkColor":"rgba(253, 248, 240, 0.08)","animate":"shimmer","shimmerColor":"rgba(196, 92, 38, 0.08)","darkShimmerColor":"rgba(240, 180, 41, 0.1)","speed":"1.8s"})

registerBones({
  "learn-course-card": _learn_course_card,
  "practice-card": _practice_card,
  "community-message": _community_message,
})
